executable('base_project_app',
  sources: ['main.c'],
  dependencies: [libbase_project_dep],
  install: true
)

executable('synthesizer_example',
  sources: ['example.c'],
  dependencies: [libbase_project_dep],
  install: true
)
executable('melody',
  sources: ['melody.c'],
  dependencies: [libbase_project_dep],
  install: true
)